---
- hosts: all

  become: yes
  become_method: sudo
  remote_user: ubuntu

  tasks:
    - name: run ls
      shell: echo JAVA_HOME
      # cat /usr/share/tomcat/logs/catalina.out
      register: data

    - debug: 
        msg: "{{ data.stdout }}"